version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - back-tier
    command: npm run start:dev

  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - 4001:5432
    volumes:
      - postgres:/data/db
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - back-tier

networks:
  back-tier:

volumes:
  postgres: